name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resouce Group rg-githubactions with AZ CLI
        uses: Azure/cli@1.0.4
        with:
          azcliversion: 2.3.0
          inlinescript: |
            az deployment sub create --location "East US" --template-file ./arm-templates/resourcegroup.json
