name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

- name: Deploy Resource Group rg-githubactions
  uses: Azure/arm-deploy@v1
  with:
    scope: subscription
    subscriptionId: 8ac7758a-404d-426b-b42c-a455d37238a0
    region: East US
    template: ./arm-templates/resourcegroup.json
    deploymentname: rg-githubactions